# Generated by Django 3.2.9 on 2022-03-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
